# Generated by Django 5.2.4 on 2025-08-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customers_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customers',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
    ]
