# Generated by Django 5.2.4 on 2025-08-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customers_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
